config/routes.rb
Thamira::Application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :eb_bills, only: [:index, :create, :update, :edit] do
    get "search", on: :collection
    get "export", on: :collection
    get 'print', on: :member
  end

  resources :courier_bills, only: [:index, :create, :update, :edit] do
    get "search", on: :collection
    get "export", on: :collection
    get 'print', on: :member
  end

  resources :payments_bills, only: [:index, :create, :update, :edit] do
    get "search", on: :collection
    get "export", on: :collection
    get 'print', on: :member
  end

  resources :cloths_bills, only: [:index, :create, :update, :edit] do
    get "search", on: :collection
    get "export", on: :collection
    get 'print', on: :member
  end

  resources :service_bills, only: [:index, :create, :update, :edit] do
    get "search", on: :collection
    get "export", on: :collection
    get 'print', on: :member
  end

  resources :ticket_bills, only: [:index, :create, :update, :edit] do
    get "search", on: :collection
    get "export", on: :collection
    get 'print', on: :member
  end

  resources :enquiries, only: [:index, :create, :update, :edit] do
    get "search", on: :collection
    get "export", on: :collection
    get 'print', on: :member
  end

  resources :billing_bills, only: [:index, :create, :update, :edit] do
    get "search", on: :collection
    get "export", on: :collection
    get 'print', on: :member
  end

  ActiveAdmin.routes(self)

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  

end

app/models/eb_bill.rb
class EbBill < ActiveRecord::Base
	belongs_to :user
	validates :service_name, :service_number, :mobile_number, :amount, :total, :bill_number, :user, presence: true
	validates :amount, :total, numericality: {greater_than_or_equal_to: 1}
	validates :bill_number, uniqueness: true
	before_validation :set_bill_number, :set_total

	def bill_number
		return super if self.persisted?
		last_bill_number = EbBill.today_bills.first.try(:bill_number)
		if last_bill_number.nil?
			bill_no = "A" + "#{Time.zone.now.strftime("%y%m%d")}-0001"
		else
			bill_no = last_bill_number.next
		end
	end
	def self.today_bills(options={})
		user = options.delete(:user)
		if user
			where("DATE(created_at) = DATE(?) AND user_id = ?", Time.zone.now, user.id).order("created_at desc")
		else
			where("DATE(created_at) = DATE(?)", Time.zone.now).order("created_at desc")
		end
	end
	def self.last_10_bills(options={})
		user = options.delete(:user)
		if user
			where(user: user).order('created_at DESC').limit(10)
		else
			order("created_at DESC").limit(10)
		end
	end
	def self.bills_at(date, options={})
		user = options.delete(:user)
		if user
			where("DATE(created_at) = DATE(?) AND user_id = ?", date, user.id).order("created_at asc")
		else
			where("DATE(created_at) = DATE(?)", date).order("created_at asc")
		end
	end

	private
	def set_bill_number
		self.bill_number = self.bill_number
	end
	def set_total
		self.total = self.amount + ((self.amount > 100) ? 10 : 5) if self.amount
	end
end

app/controllers/eb_bills_controller.rb
class EbBillsController < ApplicationController
	around_filter :catch_not_found
	load_and_authorize_resource only: [:edit, :update, :print]
	authorize_resource except: [:edit, :update]

	def index
		@eb = EbBill.new
		@today_bills = EbBill.today_bills(user: current_user)
		@today_bills_amount = @today_bills.sum(:amount)
		@today_bills_total_amount = @today_bills.sum(:total)
		@last_10_bills = EbBill.last_10_bills(user: current_user)
	end
	def create
		@eb = EbBill.new(eb_params)
		@eb.user ||= current_user
		if @eb.save
			flash[:notice] = "Bill Created Successfully-#{@eb.bill_number}, Total Amount:#{@eb.total}"
			redirect_to redirect_destination(@eb)
		else
			flash[:alert] = "Not Created, #{@eb.errors.full_messages.split(',')}"
			redirect_to eb_bills_path
		end
	end
	def update
		@eb = EbBill.find(params[:id])
		if @eb.update_attributes(eb_params)
			flash[:notice] = "Bill #{@eb.bill_number}, Updated Successfully"
			redirect_to redirect_destination(@eb)
		else
			flash[:alert] = "Not Updated, #{@eb.errors.full_messages.split(',')}"
			redirect_to edit_eb_bill_path(@eb)
		end
	end
	def print
		render 'print', layout: false
	end
	def edit
		@eb = EbBill.find(params[:id])
		@today_bills = EbBill.today_bills(user: current_user)
		@today_bills_amount = @today_bills.sum(:amount)
		@today_bills_total_amount = @today_bills.sum(:total)
		@last_10_bills = EbBill.last_10_bills(user: current_user)
		@eb = EbBill.find(params[:id])
		render 'index'
	end
	def search
		search_text = params[:search]
		@eb = EbBill.find_by(bill_number:search_text)
		if @eb
			redirect_to edit_eb_bill_path(@eb)
		else
			flash[:alert] = "Bill, #{search_text}, Does Not Exist!"
			redirect_to eb_bills_path
		end
	end
	def export
		export_date = params[:export_date].to_date
		@records = EbBill.bills_at(export_date, user: current_user)
		
		respond_to do |format|
			format.xls
		end
	end
	private
		def eb_params
			params.require(:eb_bill).permit(:service_name, :service_number, :mobile_number, :amount, :emergency, :user_id, :user)
		end
		def redirect_destination(bill)
			params[:commit] == "Print & Save" ? print_eb_bill_path(bill) : eb_bills_path	
		end	

		def catch_not_found
		  yield
		rescue ActiveRecord::RecordNotFound
		  redirect_to eb_bills_path, :flash => { :error => "Record not found." }
		end
end

app/views/eb_bills/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="Sheet1">
        <Table>
            <Row>
                <Cell><Data ss:Type="String">Service Name</Data></Cell>
                <Cell><Data ss:Type="String" ss:Bold='1'>Service Number</Data></Cell>
                <Cell><Data ss:Type="String" ss:Bold='1'>Amount</Data></Cell>
            </Row>
            <Row></Row>
            <% @records.each do |bill| %>
                <Row>
                    <Cell><Data ss:Type="String"><%= bill.service_name %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= bill.service_number %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= bill.amount %></Data></Cell>
                    <Cell><Data ss:Type="String" ss:Bold='1'><%= 'E' if bill.emergency %></Data></Cell>
                </Row>
            <% end %>
        </Table>
    </Worksheet>
</Workbook>

app/views/eb_bills/index.html.erb
<% content_for(:page_title) do %>
	Electricity
  <small><%= link_to "Billing", billing_bills_path %> | </small>
  <small><%= link_to "Courier", courier_bills_path %> | </small>
  <small><%= link_to "Dress", cloths_bills_path %> | </small>
  <small><%= link_to "Enquiry", enquiries_path %> | </small>
  <small><%= link_to "Payments", payments_bills_path %> | </small>
  <small><%= link_to "Service", service_bills_path %> | </small>
  <small><%= link_to "Ticket", ticket_bills_path %></small>
<% end %>
<div class="container">
	<div class="row well">
		<div class="span10">
			<div class="form-inline pull-left">
				<label>BILL NO: <b><%= @eb.bill_number %></b></label>
				<label>DATE: <b><%= Time.zone.now.strftime("%A, %d %B") %></b></label>
				<label>TIME: <b><%= Time.zone.now.strftime("%I:%M %p") %></b></label>
			</div>
			<%= link_to "New Bill",eb_bills_path, class:"pull-right btn btn-primary" %>
		</div>
	</div>

	<div class='row'>
		<div class='span8'>
			<!-- <form class="form-horizontal"> -->
			<%= form_for @eb, html: {class: "form-horizontal"} do |f| %>
				<div class="span6 no-left-margin">
					<div class="control-group">
						<!-- <label class="control-label">SERVICE NAME</label> -->
						<%= f.label :service_name, "SERVICE NAME", class: "control-label" %>
						<div class="controls">
							<!-- <input type="text" placeholder="Enter Name"> -->
							<%= f.text_field :service_name, placeholder: "Enter Name" %>
						</div>
					</div>
					<div class="control-group">
						<!-- <label class="control-label">SERVICE NUMBER</label> -->
						<%= f.label :service_number, "SERVICE NUMBER", class: "control-label" %>
						<div class="controls">
							<!-- <input type="text" placeholder="Enter Service Number"> -->
							<%= f.text_field :service_number, placeholder: "Enter Service Number" %>
						</div>
					</div>
					<div class="control-group">
						<!-- <label class="control-label">MOBILE NUMBER</label> -->
						<%= f.label :mobile_number, "MOBILE NUMBER", class: "control-label" %>
						<div class="controls">
							<!-- <input type="text" placeholder="Enter Mob. Number"> -->
							<%= f.text_field :mobile_number, placeholder: "Enter Mob. Number" %>
						</div>
					</div>
					<div class="control-group">
						<!-- <label class="control-label">AMOUNT</label> -->
						<%= f.label :amount, "AMOUNT", class: "control-label" %>
						<div class="controls">
							<!-- <input type="text" placeholder="Enter Amount"> -->
							<%= f.text_field :amount, placeholder: "Enter Amount" %>
						</div>
					</div>
					<div class="control-group">
						<!-- <label class="control-label">TOTAL</label> -->
						<%= f.label :total, "TOTAL", class: "control-label" %>
						<div class="controls">
							<!-- <input type="text" disabled placeholder="Final Amount Payable"> -->
							<%= f.text_field :total, placeholder: "Final Amount Payable", disabled: true %>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<label class="checkbox">
								<%= f.check_box :emergency, type: "checkbox" %>
								Emergency Bill?
							</label>
						</div>
					</div>
				</div>
				<div class="span2 text-center no-left-margin">
					<!-- <button type="submit" class="btn btn-primary margin-bottom-20">Print & Save</button> -->
					<%= f.submit "Print & Save", class: "btn btn-primary margin-bottom-20", id: "print_save_button", 
					data: {"disable-with" => "Processing.."} %>
					<%= f.submit "Save", class: "btn btn-primary margin-bottom-20", id: "save_button", data: {"disable-with" => "Processing.."} %>
					<!-- <button type="submit" disabled class="btn btn-primary margin-bottom-20 disabled">Save</button> -->
				</div>
			<!-- </form> -->
			<% end %>
			<div class='span2 text-center no-left-margin'>
				<!-- <button type="button" class="btn margin-bottom-20">Clear</button> -->
				<%= button_tag 'Clear!', class: "btn margin-bottom-20 clear_button" %>
				<!-- <form class="well well-small"> -->
				<%= form_tag search_eb_bills_path, method: :get, class: "well well-small" do %>
					<div class='margin-bottom-20'>
						<!-- <label class="inline-block", style="font-size:10px">Bill NO</label> -->
						<!-- <input type="text" class='span1 no-bottom-margin' placeholder="Bill No" id="eb_bill_number_text"> -->
						<%= text_field_tag 'search', params[:search], placeholder: "Bill No", class: "no-bottom-margin", id: "bill_search", style:"width:80%;font-size:12px" %>
					</div>
					<!-- <button type="button" class="btn btn-primary">Search</button> -->
					<%= submit_tag "Search", class: "btn btn-primary search_button" %>
				<!-- </form> -->
				<% end %>
			</div>
		</div>
		<div class="bills span4">
			<span class="label label-info margin-bottom-10">Last 10 Bills</span>
			<table class="table table-bordered table-condensed">
				<tr>
					<th>Bill No.</th>
					<th>Service No.</th>
					<th>Total Amt</th>
				</tr>
				<% @last_10_bills.each do |bill|%>
					<tr>
						<td><%= link_to bill.bill_number, edit_eb_bill_path(bill) %></td>
						<td><%= bill.service_number %></td>
						<td><%= bill.total %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>

	<div class="row">
		<form class="export span8" method="get" action="<%= export_eb_bills_path(format: 'xls')%>">
			<span class="label label-info">Export Data</span>
			<div>
				<input type="text" style="margin-top:10px" id="date_picker" placeholder="Select Date" name="export_date">
				<button type="submit" class="btn btn-primary" id="export_button">Export</button>
			</div>
		</form>
		<div class="report span4 well well-small no-left-margin">
			<span class="label label-info margin-bottom-10">Todays Report</span>
			<table class="table table-bordered table-condensed">
				<tr>
					<th>Total Bills</th>
					<th>Total Amt</th>
					<th>Total Bill Amt</th>
				</tr>
				<tr>
					<td><%= @today_bills.length %></td>
					<td><%= (@today_bills_total_amount - @today_bills_amount) * 0.8 %></td>
					<td><%= @today_bills_total_amount %></td>
				</tr>	
			</table>
		</div>
	</div>
</div>

app/views/eb_bills/print.html.erb
<html>
	<head>
	  <title>Thamira</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class='well'>
			<div class="clearfix">
				<h1 class="text-center">THAMIRA ENTERPRISE</h1>
				<div class='hidden-print margin-bottom-20 pull-right'>
					<%= link_to "New Bill", eb_bills_path, class: 'btn btn-primary' %>
				</div>
				<h3 class="text-center">C-RECEIPT FOR ELECTRICITY BILL</h3>
				<% {"Date" => @eb_bill.updated_at.to_date, "Bill Number" => @eb_bill.bill_number, "Service Number" => @eb_bill.service_number, "Service Name" => @eb_bill.service_name, "Total" => @eb_bill.total}.each do |k,v| %>
					<div class='span12'>
							<div class='span6'><%= k %></div>
							<div class='span5'><strong><%= v %></strong></div>
					</div>
				<% end %>
			</div>
		</div>
		<script type="text/javascript">
			window.print();
		</script>
	</body>
</html>